# The recommended basic settings for GNN
out_dir: results
accelerator: 'cuda'
devices: 1
use_wandb: True
dataset:
  format: PyG
  name: TU_ZINC # for TUDatasets, the right format is TU_{name}, e.g. TU_MUTAG, TU_PTC_FM, TU_PROTEINS,
  task: graph
  task_type: regression
  transductive: false # since we are doing node!
  split: [0.8, 0.1, 0.1] # for graph tasks, the split is loader (create_loader()).
  pre_transform: "lift_and_wire"
  transform: None # none
lift:
  data_model: cell_complex # alternatively: simplicial_complex
  init_edges: True
  init_rings: True
  init_method: sum
  method: rings
  max_induced_cycle_length: 5
wiring:
  adjacency_types: ["boundary","upper"]
train:
  batch_size: 16
  eval_period: 50 # what does this mean?
  ckpt_period: 100 # what does this mean?
  sampler: 'saint_rw' # 'saint_rw', 'saint_node', 'saint_edge'
  sample_node: True
  node_per_graph: 32
  walk_length: 8

model:
  type: gnn
  loss_fun: mse # mse
  graph_pooling: hetero_add_pooling # type_readout
gnn:
  graph_type: "hetero"
  layers_pre_mp: 1
  layers_mp: 3 # hyperparameter search
  layers_post_mp: 1 # hyperparameter search
  dim_inner: 8 # give as list of length # total layers - 1 or dict {pre_inner: [], mp_inner: [], post_inner: []}
  layer_type: hanconv # hanconv, hgtconv # requires graph_type == hetero
  stage_type: skipconcat
  batchnorm: true # currently not supported, must be set to false
  act: prelu # hyperparameter search
  dropout: 0.2 # Hyperparameter search
  agg: add # type_specific_aggregation: at the moment, aggregations ignore types and other information!
  normalize_adj: false # not sure if applicable
  heteroconv:
    _0_cell_0_cell: 'ginconv'
    _0_cell_1_cell: 'gatconv'
    _1_cell_0_cell: 'gatconv'
    _1_cell_1_cell: 'ginconv'
    _1_cell_2_cell: 'sageconv'
    _2_cell_1_cell: 'sageconv'
    _2_cell_2_cell: 'ginconv'
    _2_cell_3_cell: 'sageconv'
    _3_cell_2_cell: 'sageconv'
    _3_cell_3_cell: 'ginconv'
optim:
  optimizer: adam
  base_lr: 0.05
  max_epoch: 200
